/**
 * Beads Service
 * Responsible for improving "Agent Memory" by persisting state to a Git-Native format.
 * This acts as the bridge between BushidoOS (Orchestrator) and Cursor/Windsurf (Worker).
 */

import { ProjectState, StageType } from '../types';
import { SpecSchema, BeadsContext, CursorRules, FeatureSpec } from '../types/beads';
// import { commitFile } from './githubService'; // We will integrate this, for now we assume local FS simulation or future hook

export const BEADS_DIR = '.bushido';
export const SPEC_FILE = 'spec.json';
export const CONTEXT_FILE = 'strategy.md';
export const RULES_FILE = '.cursorrules';

// Circuit breaker: if the server is down, stop trying for a while
let _syncServerDown = false;
let _syncServerRetryAt = 0;
const SYNC_BACKOFF_MS = 60_000; // 60s backoff after failure

// Debounce: only sync once per 5 seconds during rapid updates
let _syncDebounceTimer: ReturnType<typeof setTimeout> | null = null;
let _pendingSyncProject: ProjectState | null = null;

/**
 * Main entry point: Syncs internal state to the external "Beads" folder.
 * Debounced and circuit-broken to avoid spamming localhost:3001 during streaming.
 */
export async function syncBeadsToRepo(project: ProjectState): Promise<void> {
    // Circuit breaker: skip if server is known to be down
    if (_syncServerDown && Date.now() < _syncServerRetryAt) {
        return;
    }

    // Debounce: batch rapid calls
    _pendingSyncProject = project;
    if (_syncDebounceTimer) return; // Already scheduled

    _syncDebounceTimer = setTimeout(() => {
        _syncDebounceTimer = null;
        const proj = _pendingSyncProject;
        _pendingSyncProject = null;
        if (proj) _doSync(proj);
    }, 5000);
}

async function _doSync(project: ProjectState): Promise<void> {
    const spec = generateSpec(project);
    const context = generateContext(project);
    const rules = generateCursorRules(project);

    const filesToSync = [
        { path: `${BEADS_DIR}/${SPEC_FILE}`, content: JSON.stringify(spec, null, 2) },
        { path: `${BEADS_DIR}/${CONTEXT_FILE}`, content: context },
        { path: RULES_FILE, content: rules }
    ];

    try {
        const response = await fetch('http://localhost:3001/api/sync', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ files: filesToSync })
        });

        if (response.ok) {
            _syncServerDown = false;
            console.log('[Beads] Successfully synced to local disk via SyncServer.');
        } else {
            _syncServerDown = true;
            _syncServerRetryAt = Date.now() + SYNC_BACKOFF_MS;
            console.warn('[Beads] SyncServer returned error. Backing off for 60s.');
        }
    } catch (e) {
        _syncServerDown = true;
        _syncServerRetryAt = Date.now() + SYNC_BACKOFF_MS;
        // Only log once, not on every chunk
        console.warn('[Beads] SyncServer unavailable. Will retry in 60s.');
    }
}

/**
 * Transforms unstructured artifacts into a strict JSON Spec
 * Parses actual PRODUCT_SPEC JSON content when available.
 */
function generateSpec(project: ProjectState): SpecSchema {
    const productSpec = project.artifacts[StageType.PRODUCT_SPEC]?.content || '';

    // Try to parse the actual structured JSON from Product Spec
    try {
        const jsonMatch = productSpec.match(/```json\n([\s\S]*?)\n```/);
        if (jsonMatch) {
            return JSON.parse(jsonMatch[1]) as SpecSchema;
        }
        if (productSpec.trim().startsWith('{')) {
            return JSON.parse(productSpec) as SpecSchema;
        }
    } catch (e) {
        console.warn('[BeadsService] Failed to parse Product Spec JSON, using fallback:', e);
    }

    // Fallback: minimal spec from project idea
    return {
        id: project.id,
        title: project.idea,
        description: `Strategy spec for: ${project.idea}`,
        version: '1.0.0',
        lastUpdated: new Date().toISOString(),
        definitions: {
            featureFlags: [],
            userRoles: ['user', 'admin'],
            entities: {}
        },
        features: [{
            id: 'feat-1',
            name: 'Core MVP',
            userStory: `As a user, I want ${project.idea} so that I can solve my problem.`,
            acceptanceCriteria: ['App loads', 'User can log in'],
            priority: 'critical'
        }],
        constraints: {
            techStack: ['React', 'TypeScript', 'Vite'],
            codingStandards: ['ESLint', 'Prettier'],
            excludedPatterns: ['Class Components']
        }
    };
}

/**
 * Generates the high-level strategy context
 */
function generateContext(project: ProjectState): string {
    const strategy = [
        `# Project Strategy: ${project.idea}`,
        `> Generated by BushidoOS on ${new Date().toLocaleDateString()}`,
        '',
        '## Market Analysis',
        project.artifacts[StageType.MARKET_ANALYSIS]?.content || '(Not yet defined)',
        '',
        '## Solution Concept',
        project.artifacts[StageType.SOLUTION_CONCEPT]?.content || '(Not yet defined)',
        '',
        '## Target Audience',
        project.artifacts[StageType.USER_PERSONA]?.content || '(Not yet defined)',
        '',
        '## Execution Roadmap',
        project.artifacts[StageType.EXECUTION_ROADMAP]?.content || '(Not yet defined)'
    ].join('\n');

    return strategy;
}

/**
 * Generates the Dynamic .cursorrules file
 * This is the "Secret Sauce" that makes Cursor smart.
 */
function generateCursorRules(project: ProjectState): string {
    return `
# BushidoOS Generated Rules for Cursor
# DO NOT EDIT MANUALLY - This file is auto-synced from the Orchestrator.

# 1. STRATEGIC CONTEXT
You are working on "${project.idea}".
Before writing any code, you MUST read:
- .bushido/strategy.md (High-level goals)
- .bushido/spec.json (Strict constraints)

# 2. TECH STACK
- Frontend: React + Vite + Tailwind CSS
- Backend: Supabase (Edge Functions + Postgres)
- Language: TypeScript (Strict Mode)

# 3. BEHAVIORAL RULES
- **No Hallucinations**: Only implement features listed in 'spec.json'.
- **Atomic Commits**: Group changes by feature ID (e.g., "feat-1").
- **Design System**: Use the components in 'src/components/ui'. Do not create new styles if they exist.

# 4. CRITICAL INSTRUCTIONS
If you are unsure about a requirement, STOP and ask the user to update the Spec in BushidoOS.
Do not make assumptions about business logic.
`.trim();
}
