/**
 * Export Service for BushidoOS
 * Generates the .bushido/ bundle for Agent-Ready Handoff
 */

import JSZip from 'jszip';
import { ProjectState, StageType, Artifact, STAGE_CONFIG } from '../types';

/**
 * Generate a SHA-256 hash of content for sync state tracking
 */
async function hashContent(content: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(content);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('').slice(0, 16);
}

/**
 * Generate .cursorrules content for Cursor/Windsurf
 */
export function generateCursorRules(project: ProjectState): string {
  const productSpec = project.artifacts[StageType.PRODUCT_SPEC];
  const solution = project.artifacts[StageType.SOLUTION_CONCEPT];

  // Extract tech stack from product spec if available
  let techStack = "Not specified";
  if (productSpec?.content) {
    const stackMatch = productSpec.content.match(/##.*Tech Stack.*\n([\s\S]*?)(?=\n##|$)/i);
    if (stackMatch) {
      techStack = stackMatch[1].trim().slice(0, 500);
    }
  }

  return `# BushidoOS Project Rules
# Generated from validated strategy artifacts
# Last updated: ${new Date().toISOString()}

## Project Overview
${project.idea}

## Tech Stack Constraints
${techStack}

## Architecture Guidelines
${solution?.content ? (extractSection(solution.content, 'Core Value Proposition', 300) || extractSection(solution.content, 'System Architecture', 300)) : 'See architecture.md for details.'}

## Code Quality Rules
- Follow the architectural patterns defined in architecture.md
- All features must align with the user persona in personas/primary_user.md
- Validate against the spec.md before implementing new features
- Use meaningful commit messages referencing spec sections

## DO NOT
- Deviate from the defined tech stack without updating spec.md
- Add features not in the roadmap without strategic justification
- Use placeholder or TODO comments in production code
- Ignore error handling and edge cases

## ALWAYS
- Write tests for critical user flows
- Document API changes
- Follow the established folder structure
- Consider the primary user persona when making UX decisions
`;
}

/**
 * Extract a section from markdown content
 */
function extractSection(content: string, sectionName: string, maxLength: number = 500): string {
  const regex = new RegExp(`##.*${sectionName}.*\\n([\\s\\S]*?)(?=\\n##|$)`, 'i');
  const match = content.match(regex);
  if (match) {
    return match[1].trim().slice(0, maxLength);
  }
  return 'See full document for details.';
}

/**
 * Generate README.md for the .bushido folder
 */
function generateReadme(project: ProjectState): string {
  const market = project.artifacts[StageType.MARKET_ANALYSIS];

  return `# ${project.idea}

> Strategy artifacts generated by [BushidoOS](https://bushidoos.dev)
> Last synced: ${new Date().toISOString()}

## Quick Overview

This folder contains validated product strategy documents designed to guide AI coding agents and maintain consistency between product vision and implementation.

## Contents

| File | Purpose |
|------|---------|
| \`.cursorrules\` | Constraints for Cursor/Windsurf AI |
| \`spec.md\` | Full product specification & PRD |
| \`architecture.md\` | System design with diagrams |
| \`personas/primary_user.md\` | Target user empathy map |
| \`roadmap.md\` | OKRs and execution timeline |
| \`.sync-state.json\` | Sync metadata (do not edit) |

## Usage with AI Agents

### Cursor / Windsurf
The \`.cursorrules\` file is automatically detected and applied.

### Other Agents
Reference \`spec.md\` in your system prompt:
\`\`\`
Read the product spec at .bushido/spec.md and implement features according to this specification.
\`\`\`

## Market Context
${market?.content ? (extractSection(market.content, '🚨 Market Reality', 200) || extractSection(market.content, 'Problem', 200)) : 'See spec.md for market analysis.'}

---
*Maintained by BushidoOS • The Spec-Driven Development Platform*
`;
}

/**
 * Generate spec.md combining PRD-relevant artifacts
 */
function generateSpec(project: ProjectState): string {
  const market = project.artifacts[StageType.MARKET_ANALYSIS];
  const product = project.artifacts[StageType.PRODUCT_SPEC];

  let content = `# Product Specification: ${project.idea}\n\n`;
  content += `> Generated by BushidoOS on ${new Date().toLocaleDateString()}\n\n`;

  if (project.researchBrief) {
    content += `## Research Foundation\n\n${project.researchBrief.slice(0, 2000)}\n\n---\n\n`;
  }

  if (market?.content) {
    content += `## Market Analysis\n\n${market.content}\n\n---\n\n`;
  }

  if (product?.content) {
    content += `## Technical Specification\n\n${product.content}\n\n`;
  }

  return content;
}

/**
 * Generate architecture.md from solution concept
 */
function generateArchitecture(project: ProjectState): string {
  const solution = project.artifacts[StageType.SOLUTION_CONCEPT];

  let content = `# System Architecture: ${project.idea}\n\n`;
  content += `> Last updated: ${new Date().toLocaleDateString()}\n\n`;

  if (solution?.content) {
    content += solution.content;
  } else {
    content += '*Architecture not yet defined. Complete the Solution Concept stage in BushidoOS.*';
  }

  return content;
}

/**
 * Generate personas/primary_user.md
 */
function generatePersona(project: ProjectState): string {
  const persona = project.artifacts[StageType.USER_PERSONA];

  let content = `# Primary User Persona\n\n`;

  if (persona?.content) {
    content += persona.content;
    if (persona.imageUrl) {
      content += `\n\n---\n\n*AI-generated persona portrait available in BushidoOS*`;
    }
  } else {
    content += '*User persona not yet defined. Complete the User Persona stage in BushidoOS.*';
  }

  return content;
}

/**
 * Generate roadmap.md from execution roadmap
 */
function generateRoadmap(project: ProjectState): string {
  const roadmap = project.artifacts[StageType.EXECUTION_ROADMAP];

  let content = `# Execution Roadmap: ${project.idea}\n\n`;
  content += `> Last updated: ${new Date().toLocaleDateString()}\n\n`;

  if (roadmap?.content) {
    content += roadmap.content;
  } else {
    content += '*Roadmap not yet defined. Complete the Execution Roadmap stage in BushidoOS.*';
  }

  return content;
}

/**
 * Generate .sync-state.json for tracking file versions
 */
export async function generateSyncState(project: ProjectState): Promise<object> {
  const files: Record<string, { hash: string; lastModified: number }> = {};

  const artifacts = [
    { key: 'spec.md', content: generateSpec(project) },
    { key: 'architecture.md', content: generateArchitecture(project) },
    { key: 'personas/primary_user.md', content: generatePersona(project) },
    { key: 'roadmap.md', content: generateRoadmap(project) },
  ];

  for (const artifact of artifacts) {
    files[artifact.key] = {
      hash: await hashContent(artifact.content),
      lastModified: Date.now()
    };
  }

  return {
    version: '1.0.0',
    projectId: project.id,
    bushidoVersion: '0.1.0',
    generatedAt: new Date().toISOString(),
    files
  };
}

/**
 * Generate complete .bushido/ bundle as a ZIP file
 */
export async function generateBushidoBundle(project: ProjectState): Promise<Blob> {
  const zip = new JSZip();
  const bushido = zip.folder('.bushido');

  if (!bushido) throw new Error('Failed to create .bushido folder');

  // Core files
  bushido.file('.cursorrules', generateCursorRules(project));
  bushido.file('README.md', generateReadme(project));
  bushido.file('spec.md', generateSpec(project));
  bushido.file('architecture.md', generateArchitecture(project));
  bushido.file('roadmap.md', generateRoadmap(project));

  // Personas folder
  const personas = bushido.folder('personas');
  if (personas) {
    personas.file('primary_user.md', generatePersona(project));
  }

  // Sync state
  const syncState = await generateSyncState(project);
  bushido.file('.sync-state.json', JSON.stringify(syncState, null, 2));

  // Generate ZIP
  return await zip.generateAsync({ type: 'blob' });
}

/**
 * Download helper for browser
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
